### ISSUE TITLE
contact need

### ISSUE THREAD

**Issue by manuprendlair** [kaytat/SimpleProtocolServer#1]
Hello,

Sorry to use the issue request to contact you.
I am emmanuel from France.
I am beginner in android app.
I play with your android app: Simple Protocol Player.

I would like to modify it for my use.
is it possible to have the source code ?

Best regards.

Emmanuel.
e.fiancette@gmail.com

**Comment by kaytat** [comment]
Wow.  It's almost exactly one year.  I apologize for the massive delay but the good news is that the client is also on github!

https://github.com/kaytat/SimpleProtocolPlayer
